import pandas as pd
import pandas_ta as ta

# Define thresholds for ADX interpretation
ADX_TREND_STRONG = 25
ADX_TREND_WEAK = 20

def get_market_state(candles_df: pd.DataFrame, adx_period: int = 14) -> (str, float):
    """
    Analyzes the market state using the Average Directional Index (ADX).

    :param candles_df: A pandas DataFrame with candle data (must include 'high', 'low', 'close').
    :param adx_period: The period to use for the ADX calculation.
    :return: A tuple containing the market state ('Trending', 'Ranging', 'Weak Trend')
             and the latest ADX value.
    """
    if not all(col in candles_df.columns for col in ['high', 'low', 'close']):
        raise ValueError("Candles DataFrame must contain 'high', 'low', and 'close' columns.")

    if len(candles_df) < adx_period * 2:
        # Not enough data to calculate a reliable ADX
        return "Not Enough Data", 0.0

    # Calculate ADX using pandas-ta
    # The adx() method returns a DataFrame with ADX, DMP, and DMN values.
    adx_df = candles_df.ta.adx(length=adx_period)

    # Get the latest ADX value from the 'ADX_14' column (name is generated by the library)
    latest_adx = adx_df[f'ADX_{adx_period}'].iloc[-1]

    if pd.isna(latest_adx):
        return "Not Enough Data", 0.0

    # Interpret the ADX value
    if latest_adx > ADX_TREND_STRONG:
        market_state = "Trending"
    elif latest_adx < ADX_TREND_WEAK:
        market_state = "Ranging"
    else:
        market_state = "Weak Trend"

    return market_state, round(latest_adx, 2)

# Example Usage (for testing)
if __name__ == '__main__':
    # Create some sample data
    data = {
        'high': [110, 112, 115, 114, 113, 111, 109, 110, 111, 110, 108, 107, 109, 110, 112, 115, 118, 120, 122, 125],
        'low':  [105, 108, 110, 111, 110, 108, 107, 108, 109, 108, 106, 105, 107, 108, 110, 113, 116, 118, 120, 123],
        'close':[108, 110, 113, 112, 111, 110, 108, 109, 110, 109, 107, 106, 108, 109, 111, 114, 117, 119, 121, 124]
    }
    sample_df = pd.DataFrame(data)

    # Simulate a longer history for more accurate ADX
    full_sample_df = pd.concat([sample_df] * 10, ignore_index=True)

    state, adx_value = get_market_state(full_sample_df)
    print(f"Market State: {state}")
    print(f"ADX Value: {adx_value}")

    # Test with insufficient data
    short_df = full_sample_df.head(20)
    state, adx_value = get_market_state(short_df)
    print(f"\nTest with insufficient data:")
    print(f"Market State: {state}")
    print(f"ADX Value: {adx_value}")
