import pandas as pd
import numpy as np
from .base import BaseStrategy
from src.core.config import settings

class HierarchicalQuartetStrategy(BaseStrategy):
    """
    A strategy based on a hierarchical filtering of four core indicators:
    1. Trend Filter: EMA(200)
    2. Entry Trigger: RSI(14)
    3. Confirmation: OBV
    4. Risk Management: ATR (used by the backtester, not for signal generation)
    """
    def __init__(self,
                 ema_period: int = 200,
                 rsi_period: int = 14,
                 rsi_upper_band: int = 60,
                 rsi_lower_band: int = 40,
                 obv_sma_period: int = 10):
        """
        Initializes the strategy with configurable parameters.
        """
        self.ema_period = ema_period
        self.rsi_period = rsi_period
        self.rsi_upper_band = rsi_upper_band
        self.rsi_lower_band = rsi_lower_band
        self.obv_sma_period = obv_sma_period
        print("HierarchicalQuartetStrategy initialized.")

    def generate_signals(self, candles_df: pd.DataFrame) -> pd.DataFrame:
        """
        Generates trading signals based on the hierarchical model.

        :param candles_df: A DataFrame with OHLCV data and the 'core quartet' of indicators.
        :return: A DataFrame with a 'signal' column ('BUY', 'SELL', 'HOLD').
        """
        required_features = ['EMA_200', 'RSI_14', 'OBV', 'close']
        if not all(col in candles_df.columns for col in required_features):
            raise ValueError(f"Input DataFrame is missing one of the required features: {required_features}")

        df = candles_df.copy()
        df['signal'] = 'HOLD'

        # --- Filter 1: Trend Direction ---
        is_uptrend = df['close'] > df['EMA_200']
        is_downtrend = df['close'] < df['EMA_200']

        # --- Filter 2: Entry Trigger (RSI) ---
        is_buy_trigger = df['RSI_14'] < self.rsi_lower_band
        is_sell_trigger = df['RSI_14'] > self.rsi_upper_band

        # --- Filter 3: Confirmation (OBV) ---
        # A simple proxy for OBV trend confirmation.
        # For a buy signal, we want to see recent OBV strength (OBV > its SMA).
        # For a sell signal, we want to see recent OBV weakness (OBV < its SMA).
        obv_sma = df['OBV'].rolling(window=self.obv_sma_period).mean()
        is_obv_confirm_buy = df['OBV'] > obv_sma
        is_obv_confirm_sell = df['OBV'] < obv_sma

        # --- Combine Filters to Generate Signals ---
        # Buy condition: Uptrend AND RSI pullback AND OBV confirmation
        buy_conditions = (is_uptrend & is_buy_trigger & is_obv_confirm_buy)
        df.loc[buy_conditions, 'signal'] = 'BUY'

        # Sell condition: Downtrend AND RSI rally AND OBV confirmation
        sell_conditions = (is_downtrend & is_sell_trigger & is_obv_confirm_sell)
        df.loc[sell_conditions, 'signal'] = 'SELL'

        # To prevent signals from firing constantly, we can refine this to only signal on the first bar that meets the condition.
        # This can be done by checking if the previous bar's condition was not met.
        buy_signals = buy_conditions & ~buy_conditions.shift(1).fillna(False)
        sell_signals = sell_conditions & ~sell_conditions.shift(1).fillna(False)

        df['signal'] = np.where(buy_signals, 'BUY', np.where(sell_signals, 'SELL', 'HOLD'))

        print("Signals generated by HierarchicalQuartetStrategy.")
        print(f"Buy signals: {len(df[df['signal'] == 'BUY'])}")
        print(f"Sell signals: {len(df[df['signal'] == 'SELL'])}")

        return df
