import os
import pandas as pd
import numpy as np
import argparse

# Adjust the path to allow imports from the 'src' directory
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.core.config import settings
from src.strategies.confluence_engine import generate_signals

def apply_trade_outcome_labels(df: pd.DataFrame, sl_atr_mult: float, tp_atr_mult: float) -> pd.DataFrame:
    """
    Applies labels to a feature DataFrame based on the outcome of trades
    generated by the 'advanced' confluence strategy.
    The ML goal is to predict if a rule-based signal will be successful.
    """
    print("Applying new trade outcome labeling for ML model...")

    # --- Parameters ---
    print(f"Using Labeling Parameters: SL ATR Mult={sl_atr_mult}, TP ATR Mult={tp_atr_mult}")
    max_holding_periods = 100

    # Step 1: Generate signals
    df_with_signals = generate_signals(df, strategy_type='advanced')

    # Step 2: Find signals and determine outcomes using integer positions
    signal_indices_pos = np.where(df_with_signals['signal'] != 0)[0]
    print(f"Found {len(signal_indices_pos)} signals to label.")

    results = []

    for i_pos in signal_indices_pos:
        signal_row = df_with_signals.iloc[i_pos]
        entry_price = signal_row['close']
        atr_at_signal = signal_row['ATR']
        signal_type = signal_row['signal']
        original_index = df_with_signals.index[i_pos]

        if pd.isna(atr_at_signal) or atr_at_signal <= 0:
            continue

        # Calculate dynamic SL and TP levels
        if signal_type == 1:  # Long
            stop_loss_price = entry_price - (sl_atr_mult * atr_at_signal)
            take_profit_price = entry_price + (tp_atr_mult * atr_at_signal)
        else:  # Short
            stop_loss_price = entry_price + (sl_atr_mult * atr_at_signal)
            take_profit_price = entry_price - (tp_atr_mult * atr_at_signal)

        # Look ahead from the next candle using iloc
        for k_pos in range(i_pos + 1, min(i_pos + 1 + max_holding_periods, len(df_with_signals))):
            future_row = df_with_signals.iloc[k_pos]
            outcome_found = False

            if signal_type == 1:  # Long trade
                if future_row['low'] <= stop_loss_price:
                    results.append({'index': original_index, 'label': 0, 'event_end_time': future_row.name})  # SL Hit
                    outcome_found = True
                elif future_row['high'] >= take_profit_price:
                    results.append({'index': original_index, 'label': 1, 'event_end_time': future_row.name})  # TP Hit
                    outcome_found = True
            else:  # Short trade
                if future_row['high'] >= stop_loss_price:
                    results.append({'index': original_index, 'label': 0, 'event_end_time': future_row.name})  # SL Hit
                    outcome_found = True
                elif future_row['low'] <= take_profit_price:
                    results.append({'index': original_index, 'label': 1, 'event_end_time': future_row.name})  # TP Hit
                    outcome_found = True

            if outcome_found:
                break

    if not results:
        print("Warning: No trade outcomes could be determined. Returning an empty DataFrame.")
        return pd.DataFrame()

    # Step 3: Create the final labeled DataFrame
    labels_df = pd.DataFrame(results).set_index('index')

    # Explicitly merge the labels and event_end_time to ensure they are included
    final_df = df_with_signals.loc[labels_df.index].copy()
    final_df['label'] = labels_df['label']
    final_df['event_end_time'] = labels_df['event_end_time']

    # The 'signal' column is kept intentionally for use in the evaluation script.
    print(f"Finished labeling. {len(final_df)} labeled events created.")
    return final_df


def main(asset: str, timeframe: str, sl_mult: float, tp_mult: float):
    """
    Main script to apply trade outcome labels to the feature dataset.
    """
    PROCESSED_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'processed')
    LABELED_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'labeled')
    os.makedirs(LABELED_DATA_DIR, exist_ok=True)

    # 1. Load the feature dataset
    features_path = os.path.join(PROCESSED_DATA_DIR, f'{asset}_{timeframe}_features.parquet')
    try:
        features_df = pd.read_parquet(features_path)
        # The labeling function expects a DatetimeIndex
        if 'open_time' in features_df.columns:
             features_df['open_time'] = pd.to_datetime(features_df['open_time'])
             features_df.set_index('open_time', inplace=True)
        print(f"Loaded feature data for {asset} from {features_path}")
    except FileNotFoundError:
        print(f"Error: Feature file not found at {features_path}. Please run 'process_features.py' first.")
        return

    # 2. Apply the new labeling logic
    labeled_df = apply_trade_outcome_labels(features_df, sl_atr_mult=sl_mult, tp_atr_mult=tp_mult)

    if labeled_df.empty:
        print("No labels were generated. Halting execution.")
        return

    # 3. Save the labeled data
    output_path = os.path.join(LABELED_DATA_DIR, f'{asset}_{timeframe}_labeled.parquet')

    # Reset index to have a standard integer index for the ML model
    labeled_df.reset_index(inplace=True)

    labeled_df.to_parquet(output_path)

    print(f"\nSuccessfully generated and filtered labels for {asset}.")
    print(f"Labeled data saved to: {output_path}")
    print("\n--- Labeled DataFrame Info ---")
    labeled_df.info()
    print("\n--- Label Distribution ---")
    print(labeled_df['label'].value_counts(normalize=True))
    print("\n--- Sample of Labeled Data ---")
    print(labeled_df.head())


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Trade Outcome Labeling for ML Confirmation Model")
    parser.add_argument("--asset", type=str, default="BTC", help="The crypto asset to process.")
    parser.add_argument("--timeframe", type=str, default="4h", help="The OHLCV timeframe to use.")
    parser.add_argument("--sl_mult", type=float, default=1.5, help="ATR multiplier for the stop loss.")
    parser.add_argument("--tp_mult", type=float, default=2.25, help="ATR multiplier for the take profit.")
    args = parser.parse_args()

    main(asset=args.asset, timeframe=args.timeframe, sl_mult=args.sl_mult, tp_mult=args.tp_mult)
