import os
import pandas as pd
import numpy as np
import argparse

# Adjust the path to allow imports from the 'src' directory
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.strategies.confluence_engine import generate_signals

def apply_trade_outcome_labels(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applies labels to a feature DataFrame based on the outcome of trades
    generated by the 'advanced' confluence strategy.

    The ML goal is to predict if a rule-based signal will be successful.

    - Step 1: Generate signals using the 'advanced' confluence strategy.
    - Step 2: For each signal, determine the trade outcome based on dynamic SL/TP.
    - Step 3: Label the signal as 1 (TP hit) or 0 (SL hit).
    - Step 4: Return a DataFrame containing ONLY the rows where a signal was
              generated, along with the corresponding label.

    Args:
        df (pd.DataFrame): The DataFrame with features.

    Returns:
        pd.DataFrame: A filtered DataFrame with features and trade outcome labels.
    """
    print("Applying new trade outcome labeling for ML model...")

    # --- Parameters from Task 0 (.env) ---
    sl_atr_mult = 2.0
    tp_atr_mult = 3.0
    # Add a max holding period to prevent infinite loops in edge cases
    max_holding_periods = 100

    # Step 1: Generate signals for the advanced strategy
    df_with_signals = generate_signals(df, strategy_type='advanced')

    # Get the indices where a signal occurs
    signal_indices = df_with_signals[df_with_signals['signal'] != 0].index
    print(f"Found {len(signal_indices)} signals to label.")

    results = [] # To store dicts of {index: signal_index, label: 0 or 1}

    # Step 2 & 3: Determine outcome for each signal
    for i in signal_indices:
        entry_price = df_with_signals.loc[i, 'close']
        atr_at_signal = df_with_signals.loc[i, 'ATR']
        signal_type = df_with_signals.loc[i, 'signal']

        if pd.isna(atr_at_signal) or atr_at_signal == 0:
            continue # Cannot set SL/TP, skip signal

        # Calculate dynamic SL and TP levels
        if signal_type == 1: # Long
            stop_loss_price = entry_price - (sl_atr_mult * atr_at_signal)
            take_profit_price = entry_price + (tp_atr_mult * atr_at_signal)
        else: # Short
            stop_loss_price = entry_price + (sl_atr_mult * atr_at_signal)
            take_profit_price = entry_price - (tp_atr_mult * atr_at_signal)

        # Look ahead from the next candle
        outcome_found = False
        for k in range(i + 1, min(i + 1 + max_holding_periods, len(df_with_signals))):
            future_low = df_with_signals.loc[k, 'low']
            future_high = df_with_signals.loc[k, 'high']

            if signal_type == 1: # Long trade
                if future_low <= stop_loss_price:
                    results.append({'index': i, 'label': 0}) # SL Hit
                    outcome_found = True
                    break
                if future_high >= take_profit_price:
                    results.append({'index': i, 'label': 1}) # TP Hit
                    outcome_found = True
                    break
            else: # Short trade
                if future_high >= stop_loss_price:
                    results.append({'index': i, 'label': 0}) # SL Hit
                    outcome_found = True
                    break
                if future_low <= take_profit_price:
                    results.append({'index': i, 'label': 1}) # TP Hit
                    outcome_found = True
                    break

    if not results:
        print("Warning: No trade outcomes could be determined. Returning an empty DataFrame.")
        return pd.DataFrame()

    # Step 4: Create the final labeled DataFrame
    labels_df = pd.DataFrame(results).set_index('index')

    # Join the labels back to the original DataFrame (with all features)
    # and filter for only the rows that we generated a label for.
    final_df = df_with_signals.join(labels_df, how='inner')

    # The ML model should not know the signal that triggered the event,
    # as its job is to PREDICT the success of the signal.
    # We also don't need the basic indicators, only the specialized ones.
    final_df.drop(columns=['signal'], inplace=True)

    print(f"Finished labeling. {len(final_df)} labeled events created.")
    return final_df


def main(asset: str, timeframe: str):
    """
    Main script to apply trade outcome labels to the feature dataset.
    """
    PROCESSED_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'processed')
    LABELED_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'labeled')
    os.makedirs(LABELED_DATA_DIR, exist_ok=True)

    # 1. Load the feature dataset
    features_path = os.path.join(PROCESSED_DATA_DIR, f'{asset}_{timeframe}_features.parquet')
    try:
        features_df = pd.read_parquet(features_path)
        # The labeling function expects a DatetimeIndex
        if 'open_time' in features_df.columns:
             features_df['open_time'] = pd.to_datetime(features_df['open_time'])
             features_df.set_index('open_time', inplace=True)
        print(f"Loaded feature data for {asset} from {features_path}")
    except FileNotFoundError:
        print(f"Error: Feature file not found at {features_path}. Please run 'process_features.py' first.")
        return

    # 2. Apply the new labeling logic
    labeled_df = apply_trade_outcome_labels(features_df)

    if labeled_df.empty:
        print("No labels were generated. Halting execution.")
        return

    # 3. Save the labeled data
    output_path = os.path.join(LABELED_DATA_DIR, f'{asset}_{timeframe}_labeled.parquet')

    # Reset index to have a standard integer index for the ML model
    labeled_df.reset_index(inplace=True)

    labeled_df.to_parquet(output_path)

    print(f"\nSuccessfully generated and filtered labels for {asset}.")
    print(f"Labeled data saved to: {output_path}")
    print("\n--- Labeled DataFrame Info ---")
    labeled_df.info()
    print("\n--- Label Distribution ---")
    print(labeled_df['label'].value_counts(normalize=True))
    print("\n--- Sample of Labeled Data ---")
    print(labeled_df.head())


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Trade Outcome Labeling for ML Confirmation Model")
    parser.add_argument("--asset", type=str, default="BTC", help="The crypto asset to process.")
    parser.add_argument("--timeframe", type=str, default="4h", help="The OHLCV timeframe to use.")
    args = parser.parse_args()

    main(asset=args.asset, timeframe=args.timeframe)
