"""
Binary Confirmation Model Evaluator

This script evaluates the out-of-sample (OOS) predictions generated by the
`train_xgboost_model.py` script for the binary confirmation model.

Its primary purpose is to find the optimal confidence threshold for the ML model
that maximizes a chosen financial metric (e.g., Sharpe Ratio) and to report
on the performance of the hybrid strategy at that threshold.
"""
import os
import pandas as pd
import numpy as np
import argparse

# Adjust the path to allow imports from the 'src' directory
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.core.config import settings

def calculate_financial_metrics(predictions: pd.DataFrame, confidence_threshold: float):
    """
    Simulates trades for a given confidence threshold and calculates financial metrics.
    """
    s = settings.EVAL
    capital = s.INITIAL_CAPITAL
    equity_curve = [s.INITIAL_CAPITAL]
    trades_list = []

    # Filter for trades that would be taken at this threshold
    potential_trades = predictions[predictions['y_pred_proba'] > confidence_threshold]

    for _, row in potential_trades.iterrows():
        if capital <= 0: break

        # --- Position Sizing ---
        risk_in_money = capital * s.RISK_PER_TRADE
        atr_at_entry = row['ATR']
        if pd.isna(atr_at_entry) or atr_at_entry <= 0: continue

        stop_loss_distance_price = s.SL_ATR_MULT * atr_at_entry
        position_size_asset = risk_in_money / stop_loss_distance_price
        position_value_usd = position_size_asset * row['close']

        # --- PnL Calculation ---
        # The 'y_true' column directly tells us the outcome (1 for win, 0 for loss)
        is_win = row['y_true'] == 1

        if is_win:
            pnl = position_size_asset * (s.TP_ATR_MULT * atr_at_entry)
        else:
            pnl = -position_size_asset * (s.SL_ATR_MULT * atr_at_entry)

        # --- Net PnL and Capital Update ---
        entry_commission = position_value_usd * s.COMMISSION_RATE
        exit_commission = (position_value_usd + pnl) * s.COMMISSION_RATE
        slippage_cost = position_value_usd * s.SLIPPAGE_RATE
        net_pnl = pnl - entry_commission - exit_commission - slippage_cost

        capital += net_pnl
        equity_curve.append(capital)
        trades_list.append({'net_pnl': net_pnl, 'win': is_win})

    # --- Final Metrics Calculation ---
    if not trades_list:
        return {"sharpe_ratio": 0, "profit_factor": 0, "max_drawdown": 0, "win_rate": 0, "total_trades": 0, "final_capital": capital}

    total_trades = len(trades_list)
    wins = sum(1 for t in trades_list if t['win'])
    win_rate = wins / total_trades
    gross_profit = sum(t['net_pnl'] for t in trades_list if t['win'])
    gross_loss = abs(sum(t['net_pnl'] for t in trades_list if not t['win']))
    profit_factor = gross_profit / gross_loss if gross_loss > 0 else np.inf

    equity_ser = pd.Series(equity_curve)
    peak = equity_ser.cummax()
    drawdown = (equity_ser - peak) / peak
    max_drawdown = abs(drawdown.min())
    returns = equity_ser.pct_change().dropna()
    sharpe_ratio = (returns.mean() / returns.std()) * np.sqrt(365) if returns.std() > 0 else 0 # Annualized

    return {"sharpe_ratio": sharpe_ratio, "profit_factor": profit_factor, "max_drawdown": max_drawdown, "win_rate": win_rate, "total_trades": total_trades, "final_capital": capital}

def main(asset: str, timeframe: str):
    """
    Main script to evaluate the model's out-of-sample predictions.
    """
    RESULTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'results')
    REPORTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'reports')
    os.makedirs(REPORTS_DIR, exist_ok=True)

    # 1. Load the OOS predictions
    predictions_path = os.path.join(RESULTS_DIR, f'{asset}_{timeframe}_oos_predictions.parquet')
    if not os.path.exists(predictions_path):
        print(f"INFO: Predictions file not found at {predictions_path}. Skipping evaluation for {asset}. This is expected if the model could not be trained.")
        return
    try:
        predictions_df = pd.read_parquet(predictions_path)
        # The labeled file contains the ATR and close price needed for simulation
        LABELED_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'labeled')
        labeled_data_path = os.path.join(LABELED_DATA_DIR, f'{asset}_{timeframe}_labeled.parquet')
        labeled_df = pd.read_parquet(labeled_data_path)

        # Set index to join correctly
        if 'index' in labeled_df.columns:
            labeled_df = labeled_df.set_index('index')
        if 'timestamp' in predictions_df.columns:
            predictions_df = predictions_df.set_index('timestamp')

        # Join the necessary columns for financial calculation
        predictions_df = predictions_df.join(labeled_df[['ATR', 'close']])
        predictions_df.dropna(inplace=True)
    except FileNotFoundError as e:
        print(f"Error: Could not find a required data file. {e}")
        return
    except Exception as e:
        print(f"An error occurred during data loading: {e}")
        return

    # 2. Find the optimal confidence threshold via Grid Search
    optimization_metric = settings.EVAL.OPTIMIZATION_METRIC
    print(f"Finding optimal confidence threshold by maximizing '{optimization_metric}'...")
    thresholds = np.arange(0.50, 0.86, 0.01) # Finer grid for single threshold
    results = []
    for t in thresholds:
        metrics = calculate_financial_metrics(predictions_df, t)
        results.append({'confidence_threshold': t, **metrics})

    results_df = pd.DataFrame(results)

    min_trades = settings.ML.MIN_TRADES_FOR_EVAL
    realistic_results_df = results_df[results_df['total_trades'] >= min_trades]

    if realistic_results_df.empty:
        print(f"CRITICAL: No threshold combination produced the minimum required {min_trades} trades.")
        if not results_df.empty:
            # Still sort by the desired metric even if no combination is valid
            best_insufficient_row = results_df.sort_values(by=optimization_metric, ascending=False).iloc[0]
            print("Diagnostics: Best result among all combinations (below trade threshold):")
            print(best_insufficient_row)
        return

    if optimization_metric not in realistic_results_df.columns:
        print(f"CRITICAL: The specified optimization_metric '{optimization_metric}' is not a valid column in the results. Available columns: {realistic_results_df.columns.tolist()}")
        return

    best_row = realistic_results_df.loc[realistic_results_df[optimization_metric].idxmax()]
    final_metrics = best_row.to_dict()

    # 3. Generate and save the final report
    report = f"Evaluation Report for {asset} ({timeframe}) - Confirmation Model\n"
    report += "="*60 + "\n"
    report += f"Optimal Confidence Threshold: {final_metrics['confidence_threshold']:.2f}\n"
    report += "-"*60 + "\n"
    report += "Financial Metrics (at optimal threshold):\n"
    report += f"  - Sharpe Ratio (Annualized): {final_metrics['sharpe_ratio']:.4f}\n"
    report += f"  - Profit Factor: {final_metrics['profit_factor']:.4f}\n"
    report += f"  - Max Drawdown: {final_metrics['max_drawdown']:.2%}\n"
    report += f"  - Win Rate: {final_metrics['win_rate']:.2%}\n"
    report += f"  - Total Trades: {int(final_metrics['total_trades'])}\n"
    report += f"  - Final Capital: ${final_metrics['final_capital']:,.2f}\n"
    report += "="*60 + "\n"

    print(report)
    report_path = os.path.join(REPORTS_DIR, f'{asset}_{timeframe}_evaluation_report.txt')
    with open(report_path, 'w') as f:
        f.write(report)
    print(f"Evaluation report saved to: {report_path}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Binary Confirmation Model Evaluation")
    parser.add_argument("--asset", type=str, default="BTC", help="The crypto asset to evaluate.")
    parser.add_argument("--timeframe", type=str, default="1h", help="The OHLCV timeframe used.")
    args = parser.parse_args()
    main(asset=args.asset, timeframe=args.timeframe)
