import os
import pandas as pd
import argparse
import sys

# Adjust the path to allow imports from the 'src' directory
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.process_features import load_data_from_db
from src.ml.feature_generator import create_core_features
from src.strategies.hierarchical_quartet_strategy import HierarchicalQuartetStrategy
from src.core.config import settings
from sqlalchemy.orm import Session
from src.database.session import SessionLocal

def run_backtest_simulation(signals_df: pd.DataFrame):
    """
    Runs a simple backtest simulation based on BUY/SELL signals.
    Borrows logic from the original evaluate_model.py script.
    """
    print("\n--- Running Backtest Simulation ---")
    s = settings.EVAL
    capital = s.INITIAL_CAPITAL
    equity_curve = [s.INITIAL_CAPITAL]
    trades_list = []
    position = 0 # -1 for short, 1 for long, 0 for flat

    for i in range(len(signals_df)):
        row = signals_df.iloc[i]

        # --- Exit Logic ---
        if position != 0:
            entry_price = trades_list[-1]['entry_price']
            pnl_ratio = (row['close'] - entry_price) / entry_price
            if position == -1: pnl_ratio = -pnl_ratio

            # Simple exit: exit on the next bar for now.
            # A more advanced version would use ATR-based stops.
            net_pnl = capital * pnl_ratio * s.RISK_PER_TRADE # Simplified PnL
            capital += net_pnl
            equity_curve.append(capital)
            trades_list[-1]['exit_price'] = row['close']
            trades_list[-1]['pnl'] = net_pnl
            position = 0

        # --- Entry Logic ---
        if row['signal'] == 'BUY' and position == 0:
            position = 1
            trades_list.append({'entry_price': row['close'], 'signal': 'BUY'})
        elif row['signal'] == 'SELL' and position == 0:
            position = -1
            trades_list.append({'entry_price': row['close'], 'signal': 'SELL'})

    if not trades_list:
        print("No trades were generated by the strategy.")
        return None

    # --- Final Metrics Calculation ---
    total_trades = len(trades_list)
    wins = sum(1 for t in trades_list if t.get('pnl', 0) > 0)
    win_rate = wins / total_trades if total_trades > 0 else 0

    equity_ser = pd.Series(equity_curve)
    returns = equity_ser.pct_change().dropna()

    sharpe_ratio = 0
    if returns.std() > 0:
        sharpe_ratio = returns.mean() / returns.std() * np.sqrt(252) # Annualized

    peak = equity_ser.cummax()
    drawdown = (equity_ser - peak) / peak
    max_drawdown = abs(drawdown.min())

    report = f"""
--- Backtest Performance Report ---
Total Trades: {total_trades}
Win Rate: {win_rate:.2%}
Annualized Sharpe Ratio: {sharpe_ratio:.4f}
Max Drawdown: {max_drawdown:.2%}
Final Capital: ${capital:,.2f}
-----------------------------------
    """
    print(report)
    return report


def main(asset: str, timeframe: str):
    """
    Main orchestration script for backtesting a rules-based strategy.
    """
    print(f"--- Starting Rules-Based Backtest for {asset} on {timeframe} ---")

    db: Session = SessionLocal()
    try:
        # 1. Load and process data to get core features
        raw_df = load_data_from_db(db, asset, timeframe)
        if raw_df.empty:
            print("No data loaded, cannot proceed.")
            return

        df_for_features = raw_df.reset_index().rename(columns={'timestamp': 'open_time'})
        features_df = create_core_features(df_for_features)

        # 2. Instantiate the strategy
        strategy = HierarchicalQuartetStrategy()

        # 3. Generate signals
        signals_df = strategy.generate_signals(features_df)

        # 4. Run the backtest simulation
        run_backtest_simulation(signals_df)

    finally:
        db.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Rules-Based Backtesting Orchestrator")
    parser.add_argument("--asset", type=str, default="BTC", help="The crypto asset to process.")
    parser.add_argument("--timeframe", type=str, default="4h", help="The OHLCV timeframe to use.")
    args = parser.parse_args()

    main(asset=args.asset, timeframe=args.timeframe)
