"""
XGBoost Confirmation Model Trainer

This script trains a binary classification model using XGBoost. The model's goal
is to act as a confirmation layer, predicting the probability of success for a
trade signal generated by the rule-based Confluence Strategy.

Workflow:
1. Loads the labeled data, which contains only the filtered events where a
   rule-based signal occurred.
2. Defines the feature set (X) using only the specialized ML features and their lags.
3. Defines the target (y) as the binary outcome (0=Failure, 1=Success).
4. Calculates `scale_pos_weight` to handle class imbalance.
5. Splits data into training and testing sets using a time-series approach.
6. Performs hyperparameter optimization using Optuna.
7. Trains the final XGBoost model on the full training set with the best parameters.
8. Evaluates the model and saves the artifact, scaler, and feature list.
"""
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import classification_report, f1_score
from sklearn.preprocessing import StandardScaler
import joblib
import os
import sys
import argparse
import json
import optuna

# Add the project root to the python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.core.config import settings

# --- Configuration ---
MODEL_DIR = os.path.join(os.path.dirname(__file__), '..', 'models')
LABELED_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'labeled')
REPORTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'reports')
RESULTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'results')

# --- Feature Set Definition ---
# As per Task 1.2, we use ONLY the specialized features for the ML model.
SPECIALIZED_FEATURES = [
    'ema_spread_normalized', 'rsi_roc', 'adx_roc', 'di_spread',
    'atr_ratio', 'obv_slope', 'price_dist_ema'
]
# And their lags
LAGGED_FEATURES = [f'{feat}_lag_{lag}' for feat in SPECIALIZED_FEATURES for lag in [1, 2]]
FINAL_FEATURE_SET = SPECIALIZED_FEATURES + LAGGED_FEATURES

def optimize_hyperparameters_xgb(X_train, y_train, n_trials: int, scale_pos_weight: float):
    """
    Performs hyperparameter optimization for a binary XGBoost classifier.
    Skips optimization and returns defaults if the dataset is too small.
    """
    MIN_SAMPLES_FOR_OPTUNA = 20
    if len(X_train) < MIN_SAMPLES_FOR_OPTUNA:
        print(f"WARNING: Training set size ({len(X_train)}) is less than {MIN_SAMPLES_FOR_OPTUNA}. Skipping Optuna and using default parameters.")
        return {
            'n_estimators': 100,
            'learning_rate': 0.05,
            'max_depth': 5,
            'subsample': 0.8,
            'colsample_bytree': 0.8,
            'gamma': 0,
            'lambda': 1,
            'alpha': 0
        }

    def objective(trial):
        param = {
            'objective': 'binary:logistic',
            'eval_metric': 'logloss',
            'verbosity': 0,
            'booster': 'gbtree',
            'scale_pos_weight': scale_pos_weight,
            'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
            'max_depth': trial.suggest_int('max_depth', 3, 10),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'gamma': trial.suggest_float('gamma', 1e-6, 0.5, log=True),
            'lambda': trial.suggest_float('lambda', 1e-6, 1.0, log=True),
            'alpha': trial.suggest_float('alpha', 1e-6, 1.0, log=True),
            'tree_method': 'hist',
            'random_state': 42,
            'n_jobs': -1
        }
        # Adaptive number of splits for cross-validation
        n_splits = max(2, min(5, len(X_train) // 2))
        tscv = TimeSeriesSplit(n_splits=n_splits)
        scores = []
        for train_index, val_index in tscv.split(X_train):
            X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
            y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]
            if len(X_val_fold) < 1: continue
            model = xgb.XGBClassifier(**param)
            model.fit(X_train_fold, y_train_fold)
            preds = model.predict(X_val_fold)
            score = f1_score(y_val_fold, preds, average='binary', zero_division=0.0)
            scores.append(score)
        return np.mean(scores) if scores else 0

    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=n_trials)
    print(f"Best trial for XGBoost: F1-score = {study.best_value}")
    print(f"Best Params: {study.best_params}")
    return study.best_params

def train_xgboost_model(symbol: str, timeframe: str):
    print(f"\n--- Starting XGBoost Confirmation Model Training for {symbol} ---")
    labeled_data_path = os.path.join(LABELED_DATA_DIR, f'{symbol}_{timeframe}_labeled.parquet')
    try:
        labeled_df = pd.read_parquet(labeled_data_path)
    except FileNotFoundError:
        print(f"ERROR: Labeled data file not found: '{labeled_data_path}'")
        return

    if labeled_df.empty:
        print("ERROR: Labeled data is empty. Skipping training.")
        return

    # 2. Prepare Data
    X = labeled_df[FINAL_FEATURE_SET]
    y = labeled_df['label']
    print(f"Feature set shape: {X.shape}")
    print(f"Target distribution:\n{y.value_counts(normalize=True)}")

    # 3. Feature Scaling
    scaler = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), index=X.index, columns=X.columns)

    # 4. Train/Test Split
    train_size = int(len(X_scaled) * 0.8) # 80/20 split
    X_train, X_test = X_scaled[:train_size], X_scaled[train_size:]
    y_train, y_test = y[:train_size], y[train_size:]
    print(f"Training set size: {len(X_train)}, Test set size: {len(X_test)}")

    # 5. Handle Class Imbalance
    label_counts = y_train.value_counts()
    if label_counts.get(1, 0) == 0:
        print("ERROR: No positive samples (label=1) in the training set. Cannot train model.")
        return
    scale_pos_weight = label_counts[0] / label_counts[1]
    print(f"Calculated scale_pos_weight: {scale_pos_weight:.2f}")

    # 6. Model Training with Hyperparameter Optimization
    print("\n--- Hyperparameter Tuning for XGBoost (Optuna) ---")
    n_trials = settings.ML.OPTUNA_TRIALS
    print(f"Running Optuna with {n_trials} trials...")
    best_params = optimize_hyperparameters_xgb(X_train, y_train, n_trials=n_trials, scale_pos_weight=scale_pos_weight)

    print("\n--- Training Final XGBoost Model with Best Parameters ---")
    final_model = xgb.XGBClassifier(
        objective='binary:logistic',
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight,
        random_state=42,
        tree_method='hist',
        **best_params
    )
    final_model.fit(X_train, y_train)

    # 7. Final Evaluation
    print(f"\n--- Final Evaluation for XGBoost on {symbol} ---")
    y_pred = final_model.predict(X_test)
    try:
        print(classification_report(y_test, y_pred, target_names=['Failure (0)', 'Success (1)'], zero_division=0.0))
    except ValueError as e:
        print(f"Could not generate classification report. This usually happens when the test set contains only one class. Error: {e}")

    # Save OOS predictions with probabilities and original signal direction
    y_pred_proba = final_model.predict_proba(X_test)[:, 1] # Probability of success

    # Get the original signal direction for the test set
    signal_test = labeled_df.loc[y_test.index, 'signal']

    oos_df = pd.DataFrame({
        'y_true': y_test,
        'y_pred_proba': y_pred_proba,
        'signal': signal_test
    }, index=y_test.index)
    os.makedirs(RESULTS_DIR, exist_ok=True)
    oos_path = os.path.join(RESULTS_DIR, f'{symbol}_{timeframe}_oos_predictions.parquet')
    oos_df.to_parquet(oos_path)
    print(f"Out-of-sample predictions saved to {oos_path}")

    # 8. Save Model, Scaler, and Features
    os.makedirs(os.path.join(MODEL_DIR, 'production'), exist_ok=True)
    model_file = os.path.join(MODEL_DIR, 'production', f"confirmation_model_{symbol}_{timeframe}.json")
    scaler_file = os.path.join(MODEL_DIR, 'production', f"confirmation_scaler_{symbol}_{timeframe}.joblib")
    features_file = os.path.join(MODEL_DIR, 'production', f"confirmation_features_{symbol}_{timeframe}.json")

    print(f"Saving model to {model_file}")
    final_model.save_model(model_file)
    print(f"Saving scaler to {scaler_file}")
    joblib.dump(scaler, scaler_file)
    with open(features_file, 'w') as f:
        json.dump(FINAL_FEATURE_SET, f)
    print(f"Feature list saved to {features_file}")
    print(f"--- XGBoost Training for {symbol} Complete ---")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train XGBoost Confirmation Model.")
    parser.add_argument("--symbols", nargs='+', default=["BTC"], help="List of asset symbols (e.g., BTC ETH) to train on.")
    parser.add_argument("--timeframe", type=str, default="1h", help="Timeframe (e.g., '1h', '4h').")
    args = parser.parse_args()
    for symbol in args.symbols:
        train_xgboost_model(symbol=symbol, timeframe=args.timeframe)
